{
 "title": "Spring Boot Observability",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(jvm_info,application)"
    }
   },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"$app_name\", uri!=\"/actuator/prometheus\"})"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"$app_name\", outcome=\"SERVER_ERROR\"})"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{application=\"$app_name\", uri!=\"/actuator/prometheus\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"$app_name\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(jvm_memory_used_bytes{job=\"$app_name\", area=\"heap\"})\r\n  /\r\n  sum(jvm_memory_max_bytes{job=\"$app_name\", area=\"heap\"})\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    http_server_requests_seconds_count{\r\n      job=\"$app_name\",\r\n      uri!=\"/actuator/prometheus\"\r\n    }[1m]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    http_server_requests_seconds_count{\r\n      job=\"$app_name\",\r\n      status=~\"5..\"\r\n    }[1m]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Consumer Lag",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  kafka_consumergroup_lag{\r\n    consumergroup=\"$group\"\r\n  }\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Used Memory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TPS Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    http_server_requests_seconds_count{\r\n      job=\"$app_name\"\r\n    }[1m]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(\r\n    rate(\r\n      http_server_requests_seconds_bucket{\r\n        job=\"$app_name\"\r\n      }[1m]\r\n    )\r\n  ) by (le)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Produce Message TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    kafka_server_brokertopicmetrics_messagesin_total[1m]\r\n  )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\r\n  rate(\r\n    kafka_consumergroup_current_offset{\r\n      consumergroup=\"$group\"\r\n    }[1m]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(\r\n  jvm_gc_pause_seconds_sum{\r\n    job=\"$app_name\"\r\n  }[1m]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retry Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    kafka_consumer_retry_count[1m]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DLQ Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    kafka_dlq_count[1m]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "System CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$app_name\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Process CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"$app_name\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(jvm_memory_used_bytes{job=\"$app_name\", area=\"heap\"})\r\n  /\r\n  sum(jvm_memory_max_bytes{job=\"$app_name\", area=\"heap\"})\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  1 - (\r\n    disk_free_bytes{job=\"$app_name\"}\r\n    /\r\n    disk_total_bytes{job=\"$app_name\"}\r\n  )\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(process_files_open_files{job=\"$app_name\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri)(http_server_requests_seconds_sum{application=\"$app_name\"}) / sum by(uri)(http_server_requests_seconds_count{application=\"$app_name\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "JVM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Count",
     "type": "timeseries",
     "description": "1분당 GC 발생 횟수",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 556 },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{job=\"$app_name\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 556 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{job=\"$app_name\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heap Usage %",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 619 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\r\n  sum(jvm_memory_used_bytes{job=\"$app_name\", area=\"heap\"})\r\n  /\r\n  sum(jvm_memory_max_bytes{job=\"$app_name\", area=\"heap\"})\r\n) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Thread Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 619 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_threads_live_threads{job=\"$app_name\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "TPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 557 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(\r\n  rate(\r\n    http_server_requests_seconds_count{\r\n      job=\"$app_name\",\r\n      uri!=\"/actuator/prometheus\"\r\n    }[1m]\r\n  )\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 557 },
     "targets": [
      {
       "expr": "sum(\r\n  rate(\r\n    http_server_requests_seconds_count{\r\n      job=\"$app_name\",\r\n      status=~\"5..\"\r\n    }[1m]\r\n  )\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 Requests Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 589 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50,\r\n  sum(rate(http_server_requests_seconds_bucket{job=\"$app_name\"}[1m]))\r\n  by (le)\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P95 Requests Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 589 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95,\r\n  sum(rate(http_server_requests_seconds_bucket{job=\"$app_name\"}[1m]))\r\n  by (le)\r\n)",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "P99 Requests Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 589 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99,\r\n  sum(rate(http_server_requests_seconds_bucket{job=\"$app_name\"}[1m]))\r\n  by (le)\r\n)",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "Percent of 2xx Requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 597 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(uri) (http_server_requests_seconds_count{application=\"$app_name\", status=~\"2.*\", uri!=\"/actuator/prometheus\"}) / sum by(uri) (http_server_requests_seconds_count{application=\"$app_name\", uri!=\"/actuator/prometheus\"})",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Percent of 4xx Requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 597 },
     "targets": [
      {
       "expr": "sum by(uri) (http_server_requests_seconds_count{application=\"$app_name\", status=~\"4.*\", uri!=\"/actuator/prometheus\"}) / sum by(uri) (http_server_requests_seconds_count{application=\"$app_name\", uri!=\"/actuator/prometheus\"})",
       "legendFormat": "{{url}}"
      }
     ]
    },
    {
     "title": "Percent of 5xx Requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 597 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(uri) (http_server_requests_seconds_count{application=\"$app_name\", status=~\"5.*\", uri!=\"/actuator/prometheus\"}) / sum by(uri) (http_server_requests_seconds_count{application=\"$app_name\", uri!=\"/actuator/prometheus\"})",
       "legendFormat": "{{uri}}"
      }
     ]
    }
   ]
  },
  { "title": "Kafka Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Produce Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    kafka_server_brokertopicmetrics_messagesin_total[1m]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consume Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "targets": [
    {
     "expr": "sum by(consumergroup)(\r\n  rate(\r\n    kafka_consumergroup_current_offset[1m]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "targets": [
    {
     "expr": "sum by(consumergroup)(\r\n  kafka_consumergroup_lag{}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Redis Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Used Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  rate(redis_keyspace_hits_total[1m])\r\n  /\r\n  (\r\n    rate(redis_keyspace_hits_total[1m])\r\n    +\r\n    rate(redis_keyspace_misses_total[1m])\r\n  )\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evicted Keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "targets": [
    {
     "expr": "rate(redis_evicted_keys_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}